### ISSUE TITLE
BufferPool improvement

### ISSUE THREAD

**Issue by jgilbert2017** [justcoding121/StreamExtended#25]
`BufferPool` should use a `ConcurrentStack` instead of a `ConcurrentQueue`.  When implementing object caches its better to use LIFO than FIFO for numerous reasons.

However... the class is implemented so simplistically it may be worth looking into existing solutions to this problem.  If there are 2 API users of the class that happen to be interleaving requests for different buffer sizes you're probably better off with no pooling at all because it just pops the last buffer and throws it away if it doesn't match the requested length.  If the assumption is that all callers are using the same array size, then the pool should probably take that as a argument to the ctor and the Get/Put methods don't have to check size at all.

Existing stable code that I've used with success to solve a similar problem is `Microsoft.IO.RecyclableMemoryStreamManager` .  The interface is a via a MemoryStream but you may be able to just use the underlying byte arrays.

Cheers!

edit: `CustomBinaryReader.ResizeBuffer()` is not returning the resized buffer to the pool.  if you are going to stick with pooling perhaps the Resize() call should be on the pool so it can recover the smaller array.

**Comment by justcoding121** [comment]
I agree that using Stack would better take advantage of cache hit in CPU. However the logic assumes that if user changes buffer size after proxy started to run, then outdated buffers will be evicted quickly. This won't happen in a stack implementation until it happens to become empty. But I think the overhead overall would be the same in this case since the number of invalid buffers to throw away would be same. But stack does have an advantage with recently used buffers reused. So I think we should switch it to stack.

We overlooked the problem when multiple instances of proxy sharing the same buffer pool. It shouldn't be a static instance. 

I am not sure how we can do `Resizebuffer` inside BufferPool. Did you mean to combine smaller buffers in the pool in to one byte array and vice-versa when releasing? If so I am not sure if that would be efficient than creating a new bigger byte array.

**Comment by honfika** [comment]
Maybe we can use this class:
https://www.nuget.org/packages/System.Buffers/4.4.0

And consider dropping the .NET 4.5 compatibility, since it is not supported anymore (since more than 2 years ago):
https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

4.5.2 and 4.6 is still supported, but I think it would be much easier for us to require 4.6.1, since it is .net standard 2.0 compatible. Maybe with a major version number increase.

**Comment by honfika** [comment]
I mean in TWP, not only in StreamExtended.

**Comment by jgilbert2017** [comment]
I think you're on the right track... I've seen references to System.Buffers but don't have any first hand experience with it.

 I use netframework but don't have any version requirements so dropping 4.5 is fine with me!

**Comment by justcoding121** [comment]
I am fine with it.

**Comment by jgilbert2017** [comment]
i just realized i actually do have a use case for requiring 4.5.2.  i've got a deployment scenario involving machines running on a default installation of Windows 7 which can't be upgraded.

**Comment by justcoding121** [comment]
Lets hold this for now then. May be we can improve existing buffer pool until some time later people stop using Windows 7. :-) 

Meanwhile if its possible we can integrate System.Buffers for .Net standard.

**Comment by jgilbert2017** [comment]
maybe just switch to ConcurrentStack for now?

**Comment by justcoding121** [comment]
Yeah. We can create a beta version with the change to Stack.

In MS implementation of array pool in above nuget package, they are using an array of stacks for each specific buffer size. Its just a more robust solution. Our implementation would not be that different than MS implemention if we use `ConcurrentStack`, except that if user is constantly changing buffer size then a 2D array stack implementation of MS would do better with separate stacks for each buffer size.

https://github.com/dotnet/corefx/blob/master/src/System.Buffers/src/System/Buffers/DefaultArrayPoolBucket.cs

**Comment by justcoding121** [comment]
I have exposed the buffer pool to the API user with the [`IBufferPool`](https://github.com/justcoding121/StreamExtended/blob/master/StreamExtended/BufferPool/IBufferPool.cs) interface. If users want to use custom buffer pools they can always provide one by implementing the interface. 

API user is expected to provide a concrete buffer pool implementation when using this library. If not they can just pass in[ `DefaultBufferPool` ](https://github.com/justcoding121/StreamExtended/blob/master/StreamExtended/BufferPool/DefaultBufferPool.cs). So buffer pool implementations can be customized by API user in Titanium Web Proxy as well with this change.

**Comment by honfika** [comment]
@jgilbert2017 Do you still need .net 4.5.2 support?

**Comment by jgilbert2017** [comment]
@honfika no, i don't (thanks for asking).
