### ISSUE TITLE
Suspect code in CustomBufferedStream.ReadLineInternalAsync

### ISSUE THREAD

**Issue by jgilbert2017** [justcoding121/StreamExtended#26]
An unlikely case, but I don't think this is right.  Correct me if I'm wrong, but I don't think a nul char return from `reader.ReadByteFromBuffer()` means end of stream;

```
                  //end of stream
                    if (newChar == '\0')
                    {
                        return encoding.GetString(buffer, 0, bufferDataLength);
                    }
```

**Comment by honfika** [comment]
This code it there since the 1st commit:) (of TWP)

https://github.com/justcoding121/Titanium-Web-Proxy/blob/3b7ca8ec77162422ffc603fefe6a031e86da7a69/Titanium.HTTPProxyServer/Utility/CustomBinaryReader.cs

Maybe @justcoding121 copied from an example which reads null terminated strings. HTTP headers are not using null terminated strings, so I think it can be safely removed.

**Comment by justcoding121** [comment]
Thanks. Can we close this @jgilbert2017

**Comment by honfika** [comment]
@justcoding121 I wrote you in gitter
Currently TWP is using a beta version of the StreamExtended package, which is not so good.
There are not too many changes, yet, so I'd suggest to release a new stabe StreamExtended package, too.
Then update the reference in TWP and release a new stable TWP again. (After a quick test of course) Is it possbile?

**Comment by justcoding121** [comment]
Yes. That sounds good.

**Comment by justcoding121** [comment]
Please reopen if any issue arise.
