### ISSUE TITLE
Integrating this package back to TWP

### ISSUE THREAD

**Issue by honfika** [justcoding121/StreamExtended#47]
Earlier this package was createed for separating the Ssl SNI and ALPN features, but it is not really easy, since not enough to modify the ALPN in the SSL hello message.

So now this package contains 3 type of functions:
Streams: buffered, copy (Alpn adder streems are not really useful)
SSL parser, which is I think not really releated to this package.
And a buffer pool class

Stream classes are quite TWP specific, implements that methods which are needed for TWP, 
I think they are not a big deal, everybody implements it when needed. (In that way as they need)

In my opinion currently it just makes harder to modify something in it. (Which - i guess - willl be done for TPW, and probably it is a breaking change for direct users) 

So maybe you should consider merging back this package to TWP.
Do you think that anybody uses it directly?

I think we should wait for other user opinions, and if there are a lot of users who are against the merge, then leave it. Otherwise merge it to TWP.

**Comment by justcoding121** [comment]
Agree. Let's leave this package as it is. And we can copy this project into TWP repository as a new project.

**Comment by justcoding121** [comment]
You can create a PR if you wish to do that.

**Comment by justcoding121** [comment]
I imported it there.

**Comment by justcoding121** [comment]
I've revoked previously the push access you had since I wasn't sure you will be active again. I've restored it. Also, I created a branch rule that requires at least one approval for any PR to be merged and restrict direct commits to master, beta or stable branches. I will create my changes through pull requests in the future unless I need direct access to debug build issues.

**Comment by honfika** [comment]
thanks:)
